package channel

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	rootconstant "github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/model"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/relaykit/dto"
	"github.com/QuantumNous/new-api/relaykit/types"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/operation_setting"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

// requestDebugCaptureReadCloser records at most RequestDebugBodyLimit bytes as
// net/http consumes the final upstream request body. It deliberately wraps the
// outbound reader instead of reading it at log time, preserving retries and
// streaming request semantics.
type requestDebugCaptureReadCloser struct {
	io.ReadCloser
	buffer        bytes.Buffer
	fullBody      bytes.Buffer
	totalBytes    int64
	truncated     bool
	fullTruncated bool
}

func (r *requestDebugCaptureReadCloser) Read(p []byte) (int, error) {
	n, err := r.ReadCloser.Read(p)
	if n > 0 {
		r.totalBytes += int64(n)
		remaining := common2.RequestDebugBodyLimit - r.buffer.Len()
		if remaining > 0 {
			toWrite := n
			if toWrite > remaining {
				toWrite = remaining
				r.truncated = true
			}
			_, _ = r.buffer.Write(p[:toWrite])
		}
		if n > remaining {
			r.truncated = true
		}
		fullRemaining := model.RequestDebugBodyMaxBytes - int64(r.fullBody.Len())
		if fullRemaining > 0 {
			toWrite := int64(n)
			if toWrite > fullRemaining {
				toWrite = fullRemaining
				r.fullTruncated = true
			}
			_, _ = r.fullBody.Write(p[:toWrite])
		}
		if int64(n) > fullRemaining {
			r.fullTruncated = true
		}
	}
	return n, err
}

func (r *requestDebugCaptureReadCloser) debugBody(contentType string, contentLength int64) map[string]interface{} {
	return common2.RequestDebugBody(r.buffer.Bytes(), contentType, r.truncated || contentLength > common2.RequestDebugBodyLimit)
}

func (r *requestDebugCaptureReadCloser) storeBody(ctx context.Context, requestID, contentType string, contentLength int64, readErr error) error {
	if r == nil {
		return nil
	}
	truncated := r.fullTruncated || contentLength > model.RequestDebugBodyMaxBytes || readErr != nil
	return model.StoreRequestDebugBody(ctx, requestID, contentType, r.fullBody.Bytes(), r.totalBytes, truncated)
}

// applyUpstreamContentLength populates req.ContentLength when the upstream
// body is wrapped in a BodyStorage (see relay/common/outbound_body.go).
//
// net/http.NewRequest only auto-detects ContentLength for *bytes.Reader,
// *bytes.Buffer and *strings.Reader. When the body is a type-erased io.Reader
// (which is the case for ReaderOnly(BodyStorage)), the Content-Length header
// would otherwise be omitted, forcing chunked transfer encoding and breaking
// some upstreams that require an explicit Content-Length.
func applyUpstreamContentLength(req *http.Request, info *common.RelayInfo) {
	if info == nil {
		return
	}
	if info.UpstreamRequestBodySize > 0 && req.ContentLength <= 0 {
		req.ContentLength = info.UpstreamRequestBodySize
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, nil
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	// Header profile templates provide the channel's client identity headers.
	// They are applied first so explicit passthrough rules and per-header
	// overrides below can still win.
	profileHeaders, profileID, err := resolveHeaderProfileStrategyHeaders(info)
	if err != nil {
		return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
	}
	appliedProfileKeys := make([]string, 0, len(profileHeaders))
	for name, value := range profileHeaders {
		key := strings.TrimSpace(strings.ToLower(name))
		value = strings.TrimSpace(value)
		if key == "" || value == "" {
			continue
		}
		headerOverride[key] = value
		appliedProfileKeys = append(appliedProfileKeys, key)
	}
	if profileID != "" {
		logHeaderProfileApplied(info, profileID, appliedProfileKeys)
	}
	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

// selectedHeaderProfileIDs returns the header profile ids selected on the
// channel, or nil when the upstream request strategy is not enabled.
func selectedHeaderProfileIDs(info *common.RelayInfo) []string {
	if info == nil || info.ChannelMeta == nil {
		return nil
	}
	strategy := info.ChannelOtherSettings.HeaderProfileStrategy
	if strategy == nil || !strategy.Enabled {
		return nil
	}
	return strategy.SelectedProfileIDs
}

// hasSelectedHeaderProfile reports whether the channel selected the given
// header profile template.
func hasSelectedHeaderProfile(info *common.RelayInfo, profileID string) bool {
	for _, selected := range selectedHeaderProfileIDs(info) {
		if selected == profileID {
			return true
		}
	}
	return false
}

// applyCompatibilityIdentityHeaders emits the protocol-compatible client
// identity headers.
//
// These are driven by the selected header profile template so any channel can
// present a Codex/Claude Code identity. Credentials, Accept and the per-request
// dynamic ids stay owned by the relay, because a template is a static header
// table and must never carry secrets.
//
// A channel that still uses the dedicated compatibility channel types keeps
// working without a template selection: those types cannot talk to their
// upstream without these headers, so the channel type acts as a fallback.
func applyCompatibilityIdentityHeaders(c *gin.Context, req *http.Request, info *common.RelayInfo) {
	if info == nil || info.ChannelMeta == nil || !info.ShouldUseChannelTestStyle() {
		return
	}

	identity := info.ChannelOtherSettings.ClientIdentity
	codexSelected := hasSelectedHeaderProfile(info, dto.HeaderProfileIDCodexCompatible)
	claudeSelected := hasSelectedHeaderProfile(info, dto.HeaderProfileIDClaudeCodeCompatible)

	switch {
	case codexSelected || info.ChannelType == rootconstant.ChannelTypeCodexCompatibility:
		ApplyCompatibilityHeadersWithClientIdentity(
			rootconstant.ChannelTypeCodexCompatibility,
			req.Header,
			info.ApiKey,
			info.IsStream,
			"",
			identity,
		)
	case claudeSelected || info.ChannelType == rootconstant.ChannelTypeClaudeCode:
		ApplyClaudeCodeCompatibilityHeadersWithIdentity(
			req.Header,
			info.ApiKey,
			info.IsStream,
			info.EnsureClaudeCodeSessionID(),
			true,
			identity,
		)
	case info.ChannelType == rootconstant.ChannelTypeCodex:
		// OAuth credentials and account routing remain owned by the adapter;
		// the client identity is generated before Header Override is applied.
		ApplyCodexLegacyClientIdentity(req.Header, identity)
	case info.ChannelType == rootconstant.ChannelTypeOpenAI,
		info.ChannelType == rootconstant.ChannelTypeAnthropic:
		ApplyLightweightClientIdentity(req.Header, identity)
	}
}

// resolveHeaderProfileStrategyHeaders resolves the channel's header profile
// template for this request. Round robin selection is persisted per channel so
// rotation is stable across restarts and instances.
func resolveHeaderProfileStrategyHeaders(info *common.RelayInfo) (map[string]string, string, error) {
	if info == nil || info.ChannelMeta == nil {
		return nil, "", nil
	}
	strategy := info.ChannelMeta.ChannelOtherSettings.HeaderProfileStrategy
	if strategy == nil || !strategy.Enabled {
		return nil, "", nil
	}
	return service.ResolveChannelRuntimeHeaderProfileHeaders(info.ChannelMeta.ChannelId, strategy)
}

func logHeaderProfileApplied(info *common.RelayInfo, profileID string, headerKeys []string) {
	if info == nil || info.ChannelMeta == nil || len(headerKeys) == 0 {
		return
	}
	strategy := info.ChannelMeta.ChannelOtherSettings.HeaderProfileStrategy
	if strategy == nil {
		return
	}
	sort.Strings(headerKeys)
	logger.LogDebug(context.Background(), fmt.Sprintf(
		"header profile applied: channel=%d profile=%s mode=%s headers=%s",
		info.ChannelMeta.ChannelId,
		profileID,
		string(strategy.Mode),
		strings.Join(headerKeys, ","),
	))
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToHeaders(headers http.Header, headerOverride map[string]string) {
	if headers == nil {
		return
	}
	for key, value := range headerOverride {
		// Header.Set canonicalizes the new key, but it does not remove an
		// existing differently-cased map key. Delete all case variants first so
		// the override is the only value that can reach the upstream request.
		for existingKey := range headers {
			if strings.EqualFold(existingKey, key) {
				delete(headers, existingKey)
			}
		}
		headers.Set(key, value)
	}
}

// ApplyHeaderOverrideToHeaders applies explicit overrides while removing
// differently-cased existing keys so a request cannot carry duplicate values.
func ApplyHeaderOverrideToHeaders(headers http.Header, headerOverride map[string]string) {
	applyHeaderOverrideToHeaders(headers, headerOverride)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	applyHeaderOverrideToHeaders(req.Header, headerOverride)
	for key, value := range headerOverride {
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	applyCompatibilityIdentityHeaders(c, req, info)
	// Apply Header Override last so it wins over every ordinary header emitted
	// by the adaptor or the compatibility profile.
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	if info != nil && info.ChannelMeta != nil && info.ShouldUseChannelTestStyle() {
		switch info.ChannelType {
		case rootconstant.ChannelTypeOpenAI, rootconstant.ChannelTypeAnthropic:
			ApplyLightweightClientIdentity(req.Header, info.ChannelOtherSettings.ClientIdentity)
		}
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	if info != nil && info.ChannelMeta != nil && info.ShouldUseChannelTestStyle() {
		switch info.ChannelType {
		case rootconstant.ChannelTypeOpenAI, rootconstant.ChannelTypeAnthropic:
			ApplyLightweightClientIdentity(targetHeader, info.ChannelOtherSettings.ClientIdentity)
		}
	}
	// Keep the client Content-Type as an adaptor default. Header Override is
	// applied after this assignment so it remains the final value.
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToHeaders(targetHeader, headerOverride)
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", common.SanitizeURLForLog(fullRequestURL), err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) (context.CancelFunc, <-chan struct{}) {
	pingerCtx, stopPinger := context.WithCancel(context.Background())
	done := make(chan struct{})

	gopool.Go(func() {
		defer close(done)
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				logger.LogDebug(c, "SSE ping goroutine panic recovered: %v", r)
			}
			logger.LogDebug(c, "SSE ping goroutine stopped")
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			logger.LogDebug(c, "SSE ping ticker stopped")
		}()

		var pingMutex sync.Mutex
		logger.LogDebug(c, "SSE ping goroutine started")

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					logger.LogDebug(c, "SSE ping error, stopping goroutine: %s", err.Error())
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				logger.LogDebug(c, "SSE ping goroutine timeout, stopping")
				return
			}
		}
	})

	return stopPinger, done
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	mutex.Lock()
	defer mutex.Unlock()

	// Bound the write so a slow client cannot block this goroutine forever;
	// doRequest's defer waits for the pinger to exit before returning.
	helper.ExtendWriteDeadline(c)
	err := helper.PingData(c)
	if err != nil {
		logger.LogError(c, "SSE ping error: "+err.Error())
		return err
	}

	logger.LogDebug(c, "SSE ping data sent")
	return nil
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}
func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	client, err := service.GetHttpClientWithProxySettings(info.ChannelSetting.Proxy, info.ChannelSetting)
	if err != nil {
		return nil, fmt.Errorf("new proxy http client failed: %w", err)
	}
	if common2.DebugEnabled && req != nil && req.URL != nil {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport select: host=%s protocol=%s shards=%d policy=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
		))
	}

	var stopPinger context.CancelFunc
	var pingerDone <-chan struct{}
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger, pingerDone = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					<-pingerDone
					logger.LogDebug(c, "SSE ping goroutine stopped by defer")
				}
			}()
		}
	}

	// Capture only bytes that the transport consumes, and only while the explicit
	// root-controlled raw diagnostics switch is enabled.
	var bodyCapture *requestDebugCaptureReadCloser
	if common2.IsRequestDebugRawEnabled() && req != nil && req.Body != nil {
		bodyCapture = &requestDebugCaptureReadCloser{ReadCloser: req.Body}
		req.Body = bodyCapture
	}
	// Keep only the final attempt in the gin context. Retry callers reuse this
	// context, so this does not create extra persisted log entries.
	common2.SetContextKey(c, rootconstant.ContextKeyRequestDebug, map[string]interface{}{
		"upstream": requestDebugUpstream(req, bodyCapture),
	})
	resp, err := client.Do(req)
	bodyStored := false
	if bodyCapture != nil {
		requestID := c.GetString(common2.RequestIdKey)
		if requestID != "" {
			if storeErr := bodyCapture.storeBody(c.Request.Context(), requestID, req.Header.Get("Content-Type"), req.ContentLength, err); storeErr != nil {
				logger.LogWarn(c, "failed to store full request debug body: "+storeErr.Error())
			} else {
				bodyStored = true
			}
		}
	}
	requestDebug := func() map[string]interface{} {
		if bodyStored {
			return requestDebugUpstreamReference(req, bodyCapture, c.GetString(common2.RequestIdKey))
		}
		return requestDebugUpstream(req, bodyCapture)
	}
	if err != nil {
		// Preserve any bytes consumed before a transport failure as well. The
		// error log is often the diagnostic record operators need most.
		common2.SetContextKey(c, rootconstant.ContextKeyRequestDebug, map[string]interface{}{
			"upstream": requestDebug(),
		})
		logger.LogError(c, "do request failed: "+err.Error())
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}
	common2.SetContextKey(c, rootconstant.ContextKeyRequestDebug, map[string]interface{}{
		"upstream": requestDebug(),
		"response": common2.RequestDebugResponse(resp),
	})
	if common2.DebugEnabled {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport negotiated: host=%s protocol=%s shards=%d policy=%s negotiated=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
			resp.Proto,
		))
	}

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func requestDebugUpstream(req *http.Request, bodyCapture *requestDebugCaptureReadCloser) map[string]interface{} {
	debug := common2.RequestDebugUpstream(req)
	if bodyCapture != nil && debug != nil {
		for key, value := range bodyCapture.debugBody(req.Header.Get("Content-Type"), req.ContentLength) {
			debug[key] = value
		}
	}
	return debug
}

func requestDebugUpstreamReference(req *http.Request, bodyCapture *requestDebugCaptureReadCloser, requestID string) map[string]interface{} {
	debug := requestDebugUpstream(req, bodyCapture)
	if debug == nil || bodyCapture == nil {
		return debug
	}
	delete(debug, "body")
	debug["body_available"] = true
	debug["body_ref"] = requestID
	debug["body_truncated"] = bodyCapture.fullTruncated || (req.ContentLength > model.RequestDebugBodyMaxBytes) || (req.ContentLength >= 0 && bodyCapture.totalBytes < req.ContentLength)
	return debug
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	req.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(requestBody), nil
	}

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
